@startuml

class BehavioredClassifier
interface IBehavior
class Behavior
interface IStateMachine
class StateMachine
interface IRegion
class Region
interface IVertex
class Vertex
interface ITransition
class Transition

BehavioredClassifier *- IBehavior : ownedBehavior
IBehavior <.. Behavior
IBehavior <.. IStateMachine
IStateMachine <.. StateMachine
Behavior <-- StateMachine
StateMachine *- IRegion: ownedRegion
IRegion <.. Region
Region *- IVertex
IVertex <.. Vertex
Region *- ITransition
ITransition <.. Transition



@enduml